# Generated by Django 4.2.10 on 2024-02-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_custom_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="terminalcommand",
            options={
                "verbose_name": "Terminal Command",
                "verbose_name_plural": "Terminal Commands",
            },
        ),
        migrations.AddField(
            model_name="terminalcommand",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="terminalcommand",
            name="command",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
