# Generated by Django 4.2.10 on 2024-02-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_web_repl", "0002_alter_terminalcommand_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminalcommand",
            name="prompt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
